### PR TITLE
Update beta

### PR DESCRIPTION
**Pull request by kowalski7cc**

### CODE REVIEW

**Comment by kowalski7cc** [comment]
@hfiguiere @barthalion How we should proceed?

**Comment by hfiguiere** [comment]
Submitted an exception https://github.com/flathub/flatpak-builder-lint/pull/35

**Comment by barthalion** [comment]
You will need to wait a bit, the new exceptions file needs to get pulled in by the backend.

**Comment by barthalion** [comment]
Something is wrong on our end, will look into it tomorrow. It shows up in the API but for some reason the linter still complains.

```
~ ❱ http https://flathub.org/api/v2/exceptions/com.github.k4zmu2a.spacecadetpinball
HTTP/1.1 200 OK
cache-control: private
content-encoding: gzip
content-type: application/json
date: Tue, 11 Oct 2022 20:19:42 GMT
server: nginx/1.22.0
set-cookie: d159f2696eb09e3bd4f927f1913c5056=4a6b8b98e2e273e255b30094de89e60c; path=/; HttpOnly; Secure; SameSite=None
transfer-encoding: chunked
vary: Accept-Encoding

{
    "appid-uses-code-hosting-domain": "app-id predates this linter rule",
    "flathub-json-modified-publish-delay": "extra-data"
}
```

**Comment by barthalion** [comment]
bot, build

**Pull request merged**
