### PR TITLE
Upgrade SDL 2 to 2.0.22

### PR DESCRIPTION
**Pull request by Newbytee**
Tested and works

### CODE REVIEW

**Comment by Newbytee** [comment]
Hm, this seems to regress resizing of the game. With this patch, resizing it leaves large black regions in the game window. Current master does not exhibit this:

image

**Comment by kowalski7cc** [comment]
Yeah, I remember reading something SDL reverted back to X as default for some issues...

**Comment by Newbytee** [comment]
> Yeah, I remember reading something SDL reverted back to X as default for some issues...

How is that related to this?

**Comment by kowalski7cc** [comment]
Updated SDL 2 to 2.24.0

**Pull request closed without merging**
